# -*- coding: utf-8 -*-
"""SRGAN Version 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GnNpjUGXjQo3QkCtQ-gPH7gZleNTFAuY
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install torch torchvision pillow tqdm scikit-image

import os
import matplotlib.pyplot as plt
from PIL import Image

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

import torchvision.transforms as transforms
import torchvision.models as models
from torch.utils.data import random_split

from skimage.metrics import peak_signal_noise_ratio as compare_psnr
from skimage.metrics import structural_similarity as compare_ssim

dataset_path = '/content/drive/MyDrive/AVBRH Murge DATA - Copy'
print("Checking dataset path...")
print(f"Dataset path exists: {os.path.exists(dataset_path)}")
print(f"Dataset contents: {os.listdir(dataset_path)[:10]}")

class MedicalImageDataset(Dataset):
    def __init__(self, root_dir, lr_size=(64,64), hr_size=(256,256)):
        self.root_dir = root_dir

        valid_ext = ('.png', '.jpg', '.jpeg', '.bmp', '.tiff')
        self.image_filenames = [f for f in os.listdir(root_dir) if f.lower().endswith(valid_ext)]
        print(f"Found {len(self.image_filenames)} images")

        self.lr_transform = transforms.Compose([
            transforms.Resize(lr_size),
            transforms.ToTensor(),
            transforms.Normalize([0.5], [0.5])
        ])

        self.hr_transform = transforms.Compose([
            transforms.Resize(hr_size),
            transforms.ToTensor(),
            transforms.Normalize([0.5], [0.5])
        ])

    def __len__(self):
        return len(self.image_filenames)

    def __getitem__(self, idx):
        img_path = os.path.join(self.root_dir, self.image_filenames[idx])
        img = Image.open(img_path).convert('L')

        hr_img = self.hr_transform(img)
        lr_img = self.lr_transform(img)

        return lr_img, hr_img

dataset = MedicalImageDataset(dataset_path)

train_size = int(0.8 * len(dataset))
val_size = len(dataset) - train_size

train_dataset, val_dataset = random_split(
    dataset, [train_size, val_size]
)

print(f"Training samples: {len(train_dataset)}")
print(f"Validation samples: {len(val_dataset)}")

train_loader = DataLoader(
    train_dataset,
    batch_size=64,
    shuffle=True,
    num_workers=4,
    pin_memory=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=64,
    shuffle=False,
    num_workers=4,
    pin_memory=True
)

class ResidualBlock(nn.Module):
    def __init__(self, channels):
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(channels, channels, kernel_size=3, padding=1),
            nn.BatchNorm2d(channels),
            nn.PReLU(),
            nn.Conv2d(channels, channels, kernel_size=3, padding=1),
            nn.BatchNorm2d(channels)
        )
    def forward(self, x):
        return x + self.block(x)

class Generator(nn.Module):
    def __init__(self, num_residual_blocks=16, upsample_factor=4):
        super().__init__()

        assert upsample_factor in [2, 4, 8], "Unsupported upscale factor"

        self.conv1 = nn.Sequential(
            nn.Conv2d(1, 64, kernel_size=9, padding=4),
            nn.PReLU()
        )

        self.residual_blocks = nn.Sequential(
            *[ResidualBlock(64) for _ in range(num_residual_blocks)]
        )

        self.conv2 = nn.Sequential(
            nn.Conv2d(64, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64)
        )

        upsample_layers = []
        for _ in range(int(torch.log2(torch.tensor(upsample_factor)))):
            upsample_layers += [
                nn.Conv2d(64, 256, kernel_size=3, padding=1),
                nn.PixelShuffle(2),
                nn.PReLU()
            ]

        self.upsampling = nn.Sequential(*upsample_layers)

        self.conv3 = nn.Conv2d(64, 1, kernel_size=9, padding=4)
        self.tanh = nn.Tanh()

    def forward(self, x):
        out1 = self.conv1(x)
        out = self.residual_blocks(out1)
        out2 = self.conv2(out)
        out = out1 + out2
        out = self.upsampling(out)
        out = self.conv3(out)
        out = self.tanh(out)
        return out

class Discriminator(nn.Module):
    def __init__(self):
        super().__init__()
        net = []
        def d_block(in_ch, out_ch, stride=1):
            layers = [nn.Conv2d(in_ch, out_ch, kernel_size=3, stride=stride, padding=1)]
            layers += [nn.BatchNorm2d(out_ch), nn.LeakyReLU(0.2, inplace=True)]
            return layers

        net += [nn.Conv2d(1, 64, kernel_size=3, stride=1, padding=1), nn.LeakyReLU(0.2, inplace=True)]
        net += d_block(64, 64, stride=2)
        net += d_block(64, 128, stride=1)
        net += d_block(128, 128, stride=2)
        net += d_block(128, 256, stride=1)
        net += d_block(256, 256, stride=2)
        net += d_block(256, 512, stride=1)
        net += d_block(512, 512, stride=2)

        net += [nn.AdaptiveAvgPool2d(1), nn.Flatten()]
        net += [nn.Linear(512, 1024), nn.LeakyReLU(0.2, inplace=True), nn.Linear(1024, 1)]

        self.net = nn.Sequential(*net)

    def forward(self, x):
        return self.net(x)

class VGGFeatureExtractor(nn.Module):
    def __init__(self, device):
        super().__init__()
        vgg = models.vgg19(pretrained=True).features[:35].to(device).eval()
        for p in vgg.parameters():
            p.requires_grad = False
        self.vgg = vgg

    def forward(self, x):
        if x.shape[1] == 1:
            x = x.repeat(1, 3, 1, 1)
        return self.vgg(x)

def visualize_preprocessing(dataset, samples=3):
    fig, axes = plt.subplots(samples, 3, figsize=(12, 4*samples))

    for i in range(samples):
        img = Image.open(os.path.join(dataset.root_dir, dataset.image_filenames[i])).convert('L')

        lr = dataset.lr_transform(img)
        hr = dataset.hr_transform(img)

        axes[i,0].imshow(img, cmap='gray')
        axes[i,0].set_title("Original")

        axes[i,1].imshow(lr.squeeze(), cmap='gray')
        axes[i,1].set_title("LR (64×64)")

        axes[i,2].imshow(hr.squeeze(), cmap='gray')
        axes[i,2].set_title("HR (256×256)")

        for j in range(3):
            axes[i,j].axis('off')

    plt.show()

visualize_preprocessing(dataset)

def plot_sample(lr, fake_hr, hr, epoch):
    def denorm(t):
        return (t * 0.5 + 0.5).clamp(0,1).cpu().numpy()

    lr_img = denorm(lr[0,0])
    fake_img = denorm(fake_hr[0,0])
    hr_img = denorm(hr[0,0])

    plt.figure(figsize=(12,4))
    plt.subplot(1,3,1)
    plt.title("LR Input")
    plt.imshow(lr_img, cmap='gray')
    plt.axis("off")

    plt.subplot(1,3,2)
    plt.title("Generated HR")
    plt.imshow(fake_img, cmap='gray')
    plt.axis("off")

    plt.subplot(1,3,3)
    plt.title("Real HR")
    plt.imshow(hr_img, cmap='gray')
    plt.axis("off")

    plt.suptitle(f"Epoch {epoch} - Image Comparison")
    plt.tight_layout()
    plt.show()

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"\n Using device: {device}")
batch_size = 64
num_epochs = 50
lr = 1e-4

generator = Generator().to(device)
discriminator = Discriminator().to(device)
print(f"Generator params: {sum(p.numel() for p in generator.parameters()):,}")
print(f"Discriminator params: {sum(p.numel() for p in discriminator.parameters()):,}")

g_optimizer = optim.Adam(generator.parameters(), lr=1e-4, betas=(0.9, 0.999))
d_optimizer = optim.Adam(discriminator.parameters(), lr=1e-4, betas=(0.9, 0.999))

adv_criterion = nn.BCEWithLogitsLoss()
l1_criterion = nn.L1Loss()

use_perceptual = True
if use_perceptual:
    vgg_extractor = VGGFeatureExtractor(device=device)
    perceptual_criterion = nn.MSELoss()

lambda_content = 1.0
lambda_perceptual = 1e-2
lambda_adv = 1e-3
real_label = 0.9
fake_label = 0.1

scaler = torch.cuda.amp.GradScaler()
use_amp = True
psnr_history = []
ssim_history = []

def plot_sample(lr, fake_hr, hr, epoch):
    lr = denorm(lr[0,0])
    fake_hr = denorm(fake_hr[0,0])
    hr = denorm(hr[0,0])

    plt.figure(figsize=(12,4))
    plt.subplot(1,3,1)
    plt.title("LR Input")
    plt.imshow(lr, cmap='gray')
    plt.axis("off")

    plt.subplot(1,3,2)
    plt.title("Generated HR")
    plt.imshow(fake_hr, cmap='gray')
    plt.axis("off")

    plt.subplot(1,3,3)
    plt.title("Real HR")
    plt.imshow(hr, cmap='gray')
    plt.axis("off")

    plt.suptitle(f"Epoch {epoch} - Image Comparison")
    plt.show()

for epoch in range(num_epochs):
    generator.train()
    discriminator.train()
    running_d_loss = 0.0
    running_g_loss = 0.0

    for lr_imgs, hr_imgs in train_loader:
        lr_imgs = lr_imgs.to(device)
        hr_imgs = hr_imgs.to(device)


        with torch.cuda.amp.autocast(enabled=use_amp):
            fake_hr = generator(lr_imgs)


        discriminator.zero_grad()
        with torch.cuda.amp.autocast(enabled=use_amp):
            real_out = discriminator(hr_imgs)
            fake_out = discriminator(fake_hr.detach())

            real_labels = torch.full_like(real_out, real_label, device=device)
            fake_labels = torch.full_like(fake_out, fake_label, device=device)

            d_loss_real = adv_criterion(real_out, real_labels)
            d_loss_fake = adv_criterion(fake_out, fake_labels)
            d_loss = (d_loss_real + d_loss_fake) * 0.5

        scaler.scale(d_loss).backward()
        scaler.step(d_optimizer)
        scaler.update()

        generator.zero_grad()
        with torch.cuda.amp.autocast(enabled=use_amp):
            fake_out_for_g = discriminator(fake_hr)
            adv_loss = adv_criterion(fake_out_for_g, torch.full_like(fake_out_for_g, real_label, device=device))


            content_loss = l1_criterion(fake_hr, hr_imgs)

            if use_perceptual:
                feat_fake = vgg_extractor(fake_hr)
                feat_real = vgg_extractor(hr_imgs)
                perc_loss = perceptual_criterion(feat_fake, feat_real)
            else:
                perc_loss = 0.0

            g_loss = lambda_content * content_loss + lambda_perceptual * perc_loss + lambda_adv * adv_loss

        scaler.scale(g_loss).backward()

        torch.nn.utils.clip_grad_norm_(generator.parameters(), max_norm=1.0)
        scaler.step(g_optimizer)
        scaler.update()

        running_d_loss += d_loss.item()
        running_g_loss += g_loss.item()

    avg_d = running_d_loss / len(train_loader)
    avg_g = running_g_loss / len(train_loader)
    print(f"Epoch {epoch+1}/{num_epochs} | D Loss: {avg_d:.6f} | G Loss: {avg_g:.6f}")


    generator.eval()
    psnr_vals = []
    ssim_vals = []
    with torch.no_grad():

        for lr_imgs, hr_imgs in val_loader:
            lr_imgs = lr_imgs.to(device); hr_imgs = hr_imgs.to(device)
            fake_hr = generator(lr_imgs)

            def denorm(t):
                t = t * 0.5 + 0.5
                return t.clamp(0,1).cpu().numpy()
            for i in range(min(4, lr_imgs.size(0))):
                f = denorm(fake_hr[i,0])
                r = denorm(hr_imgs[i,0])

                psnr_vals.append(compare_psnr(r, f, data_range=1.0))
                try:
                    ssim_vals.append(compare_ssim(r, f, data_range=1.0))
                except ValueError:
                    pass
            break

    if psnr_vals:
        epoch_psnr = sum(psnr_vals)/len(psnr_vals)
        epoch_ssim = sum(ssim_vals)/len(ssim_vals)

        psnr_history.append(epoch_psnr)
        ssim_history.append(epoch_ssim)

        print(f" Validation PSNR: {epoch_psnr:.3f} dB, SSIM: {epoch_ssim:.4f}")


    ckpt_dir = '/content/drive/My Drive/srgan_checkpoints'
    os.makedirs(ckpt_dir, exist_ok=True)
    torch.save({
        'epoch': epoch+1,
        'generator_state_dict': generator.state_dict(),
        'g_optimizer_state_dict': g_optimizer.state_dict(),
        'discriminator_state_dict': discriminator.state_dict(),
        'd_optimizer_state_dict': d_optimizer.state_dict(),
    }, os.path.join(ckpt_dir, f'srgan_epoch_{epoch+1}.pth'))

print("Training complete.")

plt.figure(figsize=(8,5))
plt.plot(psnr_history, marker='o')
plt.title("PSNR Over Epochs")
plt.xlabel("Epoch")
plt.ylabel("PSNR (dB)")
plt.grid(True)
plt.show()

plt.figure(figsize=(8,5))
plt.plot(ssim_history, marker='o', color='orange')
plt.title("SSIM Over Epochs")
plt.xlabel("Epoch")
plt.ylabel("SSIM")
plt.grid(True)
plt.show()

checkpoint = torch.load('/content/drive/My Drive/srgan_checkpoints/srgan_epoch_50.pth')
generator.load_state_dict(checkpoint['generator_state_dict'])
generator.eval()

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

generator = Generator().to(device)
generator.eval()

checkpoint_path = '/content/drive/My Drive/srgan_checkpoints/srgan_epoch_50.pth'
checkpoint = torch.load(checkpoint_path, map_location=device)
generator.load_state_dict(checkpoint['generator_state_dict'])

print("✅ Generator loaded")

import random

idx = random.randint(0, len(val_dataset)-1)
lr_img, hr_img = val_dataset[idx]

lr_img = lr_img.unsqueeze(0).to(device)
hr_img = hr_img.unsqueeze(0).to(device)

with torch.no_grad():
    sr_img = generator(lr_img)

def denorm(t):
    t = t * 0.5 + 0.5
    return t.clamp(0,1)

lr_np = denorm(lr_img[0]).squeeze().cpu().numpy()
sr_np = denorm(sr_img[0]).squeeze().cpu().numpy()
hr_np = denorm(hr_img[0]).squeeze().cpu().numpy()

import matplotlib.pyplot as plt

plt.figure(figsize=(18,5))

plt.subplot(1,3,1)
plt.imshow(lr_np, cmap='gray')
plt.title("Low Resolution")
plt.axis('off')

plt.subplot(1,3,2)
plt.imshow(sr_np, cmap='gray')
plt.title("SRGAN Output")
plt.axis('off')

plt.subplot(1,3,3)
plt.imshow(hr_np, cmap='gray')
plt.title("Ground Truth HR")
plt.axis('off')

plt.show()

psnr_list = []
ssim_list = []

from skimage.metrics import peak_signal_noise_ratio as psnr
from skimage.metrics import structural_similarity as ssim
psnr_val = psnr(hr_np, sr_np, data_range=1.0)
ssim_val = ssim(hr_np, sr_np, data_range=1.0)

psnr_list.append(psnr_val)
ssim_list.append(ssim_val)

print(f"PSNR: {psnr_val:.2f} dB")
print(f"SSIM: {ssim_val:.4f}")

